name = "Denumpyfy"
uuid = "cecfa166-9fdc-475c-9ab0-5678dea9d294"
authors = ["Miguel Raz Guzmán Macedo <miguelraz@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
